/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
 * Generated on: 23-May-2024 16:30:15
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 1
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,14 -> [-2 2)
 * Denominator         : s16,14 -> [-2 2)
 * Scale Values        : s16,17 -> [-2.500000e-01 2.500000e-01)
 * Input               : s16,15 -> [-1 1)
 * Section Input       : s16,12 -> [-8 8)
 * Section Output      : s16,11 -> [-16 16)
 * Output              : s16,11 -> [-16 16)
 * State               : s16,15 -> [-1 1)
 * Numerator Prod      : s32,29 -> [-4 4)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s40,29 -> [-1024 1024)
 * Denominator Accum   : s40,29 -> [-1024 1024)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 * Cast Before Sum     : true
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\ProgramFiles\MATLAB\R2019b\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 3
const int NL[MWSPT_NSEC] = { 1,3,1 };
const int16_T NUM[MWSPT_NSEC][3] = {
  {
     2148,      0,      0 
  },
  {
    16384, -32768,  16384 
  },
  {
    16384,      0,      0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1 };
const int16_T DEN[MWSPT_NSEC][3] = {
  {
    16384,      0,      0 
  },
  {
    16384,  12252,   4460 
  },
  {
    16384,      0,      0 
  }
};
